# Generated by Django 3.0.8 on 2020-07-27 12:14

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 17, 44, 19, 977106), validators=[HR_tasks.models.validate_date]),
        ),
    ]
