# Generated by Django 3.0.8 on 2020-07-27 14:19

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0002_auto_20200727_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 19, 49, 1, 22343), validators=[HR_tasks.models.validate_date]),
        ),
    ]
