# Generated by Django 3.0.8 on 2020-07-27 18:48

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0004_auto_20200727_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 0, 18, 42, 933055), validators=[HR_tasks.models.validate_date]),
        ),
    ]
