# Generated by Django 3.0.8 on 2020-07-27 19:11

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0005_auto_20200728_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 0, 41, 15, 477974), validators=[HR_tasks.models.validate_date]),
        ),
    ]
