# Generated by Django 3.0.8 on 2020-07-27 20:07

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0006_auto_20200728_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 1, 37, 11, 720146), validators=[HR_tasks.models.validate_date]),
        ),
    ]
