# Generated by Django 3.0.8 on 2020-07-29 19:15

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0007_auto_20200728_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 0, 44, 41, 314215), validators=[HR_tasks.models.validate_date]),
        ),
    ]
