# Generated by Django 3.0.8 on 2020-08-02 05:37

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0009_auto_20200802_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 11, 7, 42, 478390), validators=[HR_tasks.models.validate_date]),
        ),
    ]
