# Generated by Django 3.0.8 on 2020-08-02 18:35

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0010_auto_20200802_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 0, 5, 3, 150289), validators=[HR_tasks.models.validate_date]),
        ),
    ]
