# Generated by Django 3.0.8 on 2020-08-03 05:43

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0011_auto_20200803_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 11, 13, 13, 247158), validators=[HR_tasks.models.validate_date]),
        ),
    ]
