# Generated by Django 3.1 on 2020-08-07 16:10

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0013_auto_20200803_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 21, 40, 7, 524409), validators=[HR_tasks.models.validate_date]),
        ),
    ]
