# Generated by Django 3.1 on 2020-08-07 16:14

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0014_auto_20200807_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 21, 44, 2, 94845), validators=[HR_tasks.models.validate_date]),
        ),
    ]
