# Generated by Django 3.1 on 2020-08-08 13:56

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0015_auto_20200807_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 19, 26, 10, 728391), validators=[HR_tasks.models.validate_date]),
        ),
    ]
