# Generated by Django 3.1 on 2020-08-11 09:19

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0016_auto_20200808_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='month',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1', max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 14, 49, 34, 371830), validators=[HR_tasks.models.validate_date]),
        ),
    ]
