# Generated by Django 3.1 on 2020-08-11 09:19

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0017_auto_20200811_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 14, 49, 58, 186187), validators=[HR_tasks.models.validate_date]),
        ),
    ]
