# Generated by Django 3.1 on 2020-08-11 09:21

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0018_auto_20200811_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='month',
            field=models.CharField(choices=[('1', 'Jan'), ('2', 'Feb'), ('3', 'Mar'), ('4', 'Apr'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'Aug'), ('9', 'Sep'), ('10', 'Oct'), ('11', 'Nov'), ('12', 'Dec')], default='Jan', max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 14, 51, 55, 189166), validators=[HR_tasks.models.validate_date]),
        ),
    ]
