# Generated by Django 3.1 on 2020-08-13 08:16

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0021_auto_20200811_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_US',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 46, 6, 930180), validators=[HR_tasks.models.validate_date]),
        ),
    ]
