# Generated by Django 3.1 on 2020-08-13 13:53

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0022_auto_20200813_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_US',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 19, 23, 12, 950985), validators=[HR_tasks.models.validate_date]),
        ),
    ]
