# Generated by Django 3.1 on 2020-08-17 09:51

import HR_tasks.models
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0024_auto_20200813_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 16, 21, 16, 956262), validators=[HR_tasks.models.validate_date]),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 15, 21, 16, 956262), validators=[HR_tasks.models.validate_date]),
        ),
    ]
