# Generated by Django 3.1 on 2020-08-17 19:38

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0025_auto_20200817_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='week',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', 8), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default=1, max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 2, 8, 36, 590584), validators=[HR_tasks.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 1, 8, 36, 590584), validators=[HR_tasks.models.validate_date]),
        ),
    ]
