# Generated by Django 3.0.8 on 2020-08-18 19:54

import HR_tasks.models
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0026_auto_20200818_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='year',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='month',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='approval',
            name='week',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=120),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 2, 23, 53, 513407), validators=[HR_tasks.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 1, 23, 53, 513407), validators=[HR_tasks.models.validate_date]),
        ),
    ]
