# Generated by Django 3.1 on 2020-08-19 20:27

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0027_auto_20200819_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='week',
        ),
        migrations.AddField(
            model_name='approval',
            name='week1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='week2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='week3',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='week4',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 2, 57, 20, 759835), validators=[HR_tasks.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 1, 57, 20, 759835), validators=[HR_tasks.models.validate_date]),
        ),
    ]
