# Generated by Django 3.1 on 2020-08-20 09:50

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0028_auto_20200820_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 16, 20, 54, 252083), validators=[HR_tasks.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 15, 20, 54, 252083), validators=[HR_tasks.models.validate_date]),
        ),
    ]
