# Generated by Django 3.1 on 2020-08-20 18:28

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0029_auto_20200820_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 0, 58, 40, 996428), validators=[HR_tasks.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 23, 58, 40, 996428), validators=[HR_tasks.models.validate_date]),
        ),
    ]
