# Generated by Django 3.1 on 2020-08-20 20:46

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0030_auto_20200820_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approved',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 3, 16, 49, 716200), validators=[HR_tasks.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 2, 16, 49, 716012), validators=[HR_tasks.models.validate_date]),
        ),
    ]
