# Generated by Django 3.1 on 2021-02-06 14:13

import HR_tasks.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_tasks', '0031_auto_20200821_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 20, 43, 37, 370211), validators=[HR_tasks.models.validate_date]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 19, 43, 37, 370211), validators=[HR_tasks.models.validate_date]),
        ),
    ]
