# Generated by Django 3.1 on 2020-08-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_expenses', '0003_expenses_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='document',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
