# Generated by Django 3.1 on 2020-08-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_expenses', '0004_expenses_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='document',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
