# Generated by Django 3.0.8 on 2020-07-22 13:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HR_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prob_software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue', ckeditor.fields.RichTextField()),
                ('solved', models.BooleanField(default=False)),
                ('due_by', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='low', max_length=20)),
                ('current_status', models.CharField(choices=[('active', 'active'), ('closed', 'closed'), ('onGoing', 'onGoing')], default='active', max_length=20)),
                ('impact', models.CharField(choices=[('low', 'low'), ('high', 'high')], default='low', max_length=20)),
                ('root_cause', models.CharField(max_length=200)),
                ('Symptoms', models.CharField(max_length=200)),
                ('hardware_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_inventory.Hardware', verbose_name='Hardware Related Item')),
                ('software_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HR_inventory.Software', verbose_name='Software Related Item')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='HR_problems.Prob_software')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
