# Generated by Django 3.0.8 on 2020-08-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HR_user_profiles', '0001_initial'),
        ('HR_problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prob_software',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='HR_user_profiles.Profile', verbose_name='Created BY'),
            preserve_default=False,
        ),
    ]
