# Generated by Django 3.0.8 on 2020-08-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR_problems', '0002_prob_software_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prob_software',
            name='created_by',
        ),
    ]
