# Generated by Django 3.0.8 on 2020-07-22 13:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)])),
                ('february', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(29)])),
                ('march', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)])),
                ('april', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('may', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)])),
                ('june', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('july', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)])),
                ('august', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)])),
                ('september', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('october', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)])),
                ('november', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)])),
                ('december', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31)])),
            ],
            options={
                'verbose_name_plural': 'Working Days',
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('reason', models.TextField(max_length=250)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('assign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Assign work to')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR_leaves.LeaveApplication')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
