# Generated by Django 3.0.8 on 2020-07-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
