# Generated by Django 3.0.8 on 2020-07-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_leaves', '0002_leaveapplication_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='employee',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
