# Generated by Django 3.0.8 on 2020-07-29 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HR_leaves', '0004_auto_20200728_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
